.\" Hey, EMACS: -*- nroff -*-
.\" nanorc.5 is Copyright (C) 2003 Free Software Foundation, Inc.
.\"
.\" (c) 2003 Jean-Philippe Guérard <jean-philippe.guerard@corbeaunoir.org>
.\" pour l'adaptation française
.\"
.\" This is free documentation, see the latest version of the GNU General
.\" Public License for copying conditions. There is NO warranty.
.\"
.\" Ce document est libre. Reportez-vous à la dernière version de la
.\" licence publique générale GNU (GNU GPL) pour connaître ses
.\" conditions d'utilisation. AUCUNE garantie n'est offerte.
.\"
.TH NANORC 5 "19 juin 2003 (v.f. du 25 août 2003)"
.\" Please adjust this date whenever revising the manpage.
.\" Merci de modifier ces dates à chaque mise à jour de cette page.

.SH NAME
nanorc \- fichier de configuration de l'éditeur nano du projet GNU 

.SH DESCRIPTION
Cette page de manuel décrit brièvement le fichier de configuration de 
l'éditeur \fBnano\fP du projet GNU.
.PP
\fBnano\fP est un petit éditeur sympathique et libre, qui vise à 
remplacer Pico, l'éditeur par défaut du paquet non-libre Pine. 
\fBnano\fP ne se contentant pas de copier l'interface et l'ergonomie de 
Pico, il offre également certaines fonctionnalités manquantes (ou 
désactivées par défaut) de Pico. Ces fonctionnalités sont, par exemple, 
les fonctions de recherche et de remplacement, et la possibilité de 
sauter directement à un numéro de ligne.
.PP
Le fichier \fInanorc\fP contient les paramètres par défaut de 
\fBnano\fP. Lors de son démarrage, nano commence par lire le fichier de 
configuration général \fI$SYSCONFDIR/nanorc\fP, puis lit le fichier de 
configuration personnel de l'utilisateur \fI~/.nanorc\fP.

.SH OPTIONS
Le fichier de configuration accepte une série de commandes «\ set\ » 
(activer) et «\ unset\ » (désactiver), qui permettent de définir la 
configuration de nano au démarrage sans avoir à utiliser d'options sur 
la ligne de commande.
De plus, les mots clefs «\ syntax\ » (syntaxe) et «\ color\ » (couleur) 
sont utilisés pour définir les règles de colorisation pour différents 
motifs de texte. Nano lira une commande par ligne.

Les options du fichier de configuration ont priorité sur les valeurs par 
défaut utilisées par nano. Les options données sur la ligne de commande 
permettent d'outrepasser les options du fichier de configuration.

Les options sont désactivées (unset) par défaut, sauf les options 
prenant un argument.

Les commandes et arguments reconnus sont\ :

.TP 3
\fBset/unset autoindent\fP
Active l'indentation automatique.
.TP
\fBset/unset backup\fP
Crée des copie de sécurité appelées
.IR nom_du_fichier~ .
.TP
\fBset/unset const\fP
Affiche en permanence la position du curseur dans la barre 
d'information.
.TP
\fBset/unset cut\fP
Par défaut, utilise ^K  pour couper le texte du curseur à la fin de la 
ligne, au lieu de couper la ligne entière.
.TP
\fBset fill \fIn\fP\fP
Passe automatiquement à la ligne à la colonne \fIn\fP. Si la valeur 
indiquée est 0 ou moins, la longueur de la ligne sera égale à la largeur 
de l'écran moins \fIn\fP. La valeur par défaut est -8.
.TP
\fBset/unset historylog\fP
Active l'utilisation de
.I ~/.nano_history
pour enregistrer et relire les chaînes ayant fait l'objet d'une 
recherche ou d'un remplacement.
.TP
\fBset/unset keypad\fP
Utilise l'autre gestion du pavé numérique.
.TP
\fBset/unset multibuffer\fP
Permet de charger simultanément plusieurs fichiers.
.TP
\fBset/unset noconvert\fP
Pas de conversion depuis les formats DOS et Mac.
.TP
\fBset/unset nofollow\fP
Ne suit pas les liens symboliques lors de l'écriture des fichiers.
.TP
\fBset/unset nohelp\fP
Désactive la barre d'aide affichée en bas de l'écran.
.TP
\fBset/unset nowrap\fP
Désactive le passage automatique à la ligne.
.TP
\fBset operatingdir "\fIrépertoire\fP"\fP
\fBnano\fP ne lira et n'écrira des fichiers qu'à l'intérieur du 
\fIrépertoire\fP et de ses sous-répertoires. De plus, celui-ci devient 
le répertoire courant, afin que les fichiers soient écrits dans ce 
dossier. Par défaut, cette fonction est désactivée.
.TP
\fBset/unset preserve\fP
Préserve les séquences XON et XOFF (^Q et ^S).
.TP
\fBset quotestr "\fIchaîne\fP"\fP
Définit le préfixe par défaut utilisé pour les citations dans les 
courriers électroniques. Ce préfixe est utilisé pour réaliser une 
justification correcte de ces citations. Il s'agira, si votre système le 
permet, d'une «\ expression rationnelle étendue\ ». Dans le cas 
contraire, il s'agira d'une chaîne de texte brut. Si vous disposez des 
expressions rationnelles, la valeur par défaut sera\ :

	set quotestr "^([\ \\t]*[|>:}#])+"

Sinon, ce sera ">\ ". Notez que le «\ \\t\ » ci-dessus correspond à un 
caractère de tabulation.
.TP
\fBset/unset regexp\fP
Utilise par défaut des expressions rationnelles pour les recherches.
.TP
\fBset/unset smooth\fP
Active le défilement ligne-par-ligne du texte.
.TP
\fBset speller \fIprogramme\fP\fP
Utilise le correcteur orthographique \fIprogramme\fP au lieu du 
correcteur intégré, qui s'appuie sur \fIspell\fP.
.TP
\fBset/unset suspend\fP
Autorise à suspendre nano avec ^Z.
.TP
\fBset tabsize \fIn\fP\fP
Utilise une largeur de tabulation de \fIn\fP au lieu de la valeur par 
défaut (8). Cette valeur doit être supérieur à 0.
.TP
\fBset/unset tempfile\fP
S'il a été modifié, le fichier sera sauvegardé automatiquement
sans demande de confirmation.
.TP
\fBset/unset view\fP
Interdit la modification du fichier.
.TP
.B syntax "\fIchaîne\fP" ["\fImotif_de_fichier\fP" ... ]
Définit une syntaxe nommée \fIchaîne\fP qui pourra être activé via 
l'option \fB-Y\fP, ou qui sera automatiquement activé si le nom du 
fichier en cours correspond au \fImotif_de_fichier\fP. Toutes les 
instructions de colorisation \fBcolor\fP suivantes s'appliqueront à cette 
syntaxe, jusqu'à la définition d'une nouvelle syntaxe.
.TP
.B color \fIcouleur_texte\fP[,\fIcouleur_fond\fP] "\fImotif\fP" ...
Pour la syntaxe en cours, affiche toutes les expressions correspondant à 
l'expression rationnelle \fImotif\fP en utilisant la couleur de texte 
\fIcouleur_texte\fP et éventuellement la couleur de fond 
\fIcouleur_fond\fP. Les couleurs acceptées par \fBnano\fP pour le 
texte et le fond sont\ : \fIwhite\fP (blanc), \fIblack\fP (noir), 
\fIred\fP (rouge), \fIblue\fP (bleu), \fIgreen\fP (vert), \fIyellow\fP 
(jaune), \fImagenta\fP, et \fIcyan\fP. Vous pouvez ajouter à 
ces couleurs le préfixe \fIbright\fP pour obtenir une couleur plus 
lumineuse. Si votre terminal est capable de gérer la transparence, ne 
pas spécifier de \fIcouleur_fond\fP indique à \fBnano\fP d'essayer 
d'utiliser un fond transparent.
.TP
.B color \fIcouleur_texte\fP[,\fIcouleur_fond\fP] start="\fImotif_début\fP" end="\fImotif_fin\fP"
Affiche les expressions commençant par \fImotif_début\fP et se terminant 
par \fImotif_fin\fP en utilisant la couleur de texte \fIcouleur_texte\fP 
et éventuellement la couleur de fond \fIcouleur_fond\fP. Cela permet à 
la colorisation syntaxique de s'étendre sur plusieurs lignes. Notez que 
toutes les occurrences successives de \fImotif_début\fP après le 
\fImotif_début\fP initial seront colorées jusqu'à la prochaine instance 
de \fImotif_fin\fP.

.SH FICHIERS
.TP
.I $SYSCONFDIR/nanorc
Fichier de configuration général
.TP
.I ~/.nanorc
Fichier de configuration personnel

.SH VOIR AUSSI
.PD 0
.TP
\fBnano\fP(1)
.PP
\fI/usr/share/doc/nano/examples/nanorc.sample\fP (ou son équivalent sur 
votre système)

.SH AUTEUR
Chris Allegretta <chrisa@asty.org> et d'autres (voir les fichiers
\fIAUTHORS\fP et \fITHANKS\fP pour plus d'information). Cette page de
manuel a été rédigée par Jordi Mallach <jordi@gnu.org>.

.SH TRADUCTION
Jean-Philippe Guérard <jean-philippe.guerard@corbeaunoir.org>, 2003.
