# unattributed syntax highlighting example from wiki.linuxhelp.net/

syntax "makefile" "Makefile[^/]*$"
color red "[:=]"
color magenta "\<(if|ifeq|else|endif)\>"
color blue "\$+[{(][a-Z0-9_-]+[})]"
color brightblue "^[^ 	]+:"
color green "#.*$"
