## Here is an example for Makefiles.

syntax makefile "(/((GNU)?m|M)akefile[^/]*$|\.(make|mk)$)"
magic "makefile script"
comment "#"

color red "[:=]"
color magenta "\<(if|ifeq|else|endif)\>"
color blue "\$+[{(][a-zA-Z0-9_-]+[})]"
color brightblue "^[^ 	]+:"
color green "(^|[[:space:]]+)#.*"

## Trailing whitespace.
color ,green "[[:space:]]+$"
